# Generated by Django 5.0.6 on 2024-07-03 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_alter_companyprofile_user'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshippost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='company',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='job_poster',
        ),
        migrations.AddField(
            model_name='internshippost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post.tag'),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship')], default='FT', max_length=100),
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='salary',
            field=models.CharField(blank=True, default='Not disclosed', max_length=100),
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Filled', 'Filled')], default='Open', max_length=50),
        ),
        migrations.AddIndex(
            model_name='internshippost',
            index=models.Index(fields=['job_title'], name='internship__job_tit_0832a6_idx'),
        ),
        migrations.AddIndex(
            model_name='internshippost',
            index=models.Index(fields=['location'], name='internship__locatio_95662c_idx'),
        ),
    ]
