version: "3.7"

networks:
  app-network:
    driver: bridge

services: 
  app:
    container_name: app
    build:
      context: ./infra/app
      dockerfile: Dockerfile
    image: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    networks: 
      - app-network
  
  db:
    container_name: db
    build:
      context: ./infra/pgsql
      dockerfile: Dockerfile
    image: postgres:latest
    restart: unless-stopped
    # expose:
    #  - "5432"
    ports:
      - "5433:5432"
    volumes: 
      - ./infra/pgsql/script:/docker-entrypoint-initdb.d
      - ./infra/pgsql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE} 
    networks:
      - app-network


  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports: 
        - 8989:80
    volumes: 
        - ./infra/nginx/:/etc/nginx/conf.d
    networks: 
        - app-network