version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--data-checksums
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: web
    restart: always
    command: >
      sh -c "
      pip install -r requirements.txt &&
      python manage.py migrate account && python manage.py migrate internship &&
      python manage.py migrate &&
      python manage.py createsuperuser --no-input --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL} || true &&
      python manage.py runserver 0.0.0.0:8989"
      sh -c "ls /app/**/*.py | entr -r python manage.py runserver 0.0.0.0:8989"
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
