version: '3.3'
services:  
  postgres:
    platform: 'linux/amd64'
    image: postgres:latest
    container_name: backend-postgres-local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - backend-postgres-local:/var/lib/postgresql/data/

  backend:
    platform: 'linux/amd64'
    image: backend-django:local
    container_name: backend-django-local
    build:
      context: ../../
      dockerfile: ./build-process/backend-project/docker-backend-django/Dockerfile
      args:
        APP_ENVIRONMENT: 'Local'
    volumes:
      - ../../:/home/backend-project
    ports:
      - '8989:8989'
    env_file:
      - ./local-backend.env
    depends_on:
      - postgres

volumes:
  backend-postgres-local:
  esdata:

